name: pipeline

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint:all

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Test
        run: yarn test
        env:
          CI: true

      - name: Publish Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    
  storysnaps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install
        uses: bahmutov/npm-install@v1
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      
      - name: Test
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: true
        with:
          args: yarn build-storybook && yarn workspace @betaflight/configurator storyshots
      
      - name: Publish diff
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2-preview
        with:
          name: diff
          path: |
            packages/configurator/__image_snapshots__/__diff_output__/*

  deploy-mock-api:
    runs-on: ubuntu-latest
    needs: [test, lint, storysnaps]

    steps:
      - uses: actions/checkout@v1

      - name: Login to Heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: heroku container:login 

      - name: Build
        run: docker build -t mock-api -f Dockerfile.web .

      - name: Push
        if: github.ref == 'refs/heads/master'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: 
          heroku container:push -a betaflight-mock-api web --recursive

      - name: Release
        if: github.ref == 'refs/heads/master'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: heroku container:release -a betaflight-mock-api web
  
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    needs: [test, lint, storysnaps]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Build configurator
        if: "!startsWith(github.ref, 'refs/tags/@betaflight/configurator@')"
        run: yarn workspace @betaflight/configurator build

      - name: Build and release configurator
        if: startsWith(github.ref, 'refs/tags/@betaflight/configurator@')
        run: yarn workspace @betaflight/configurator release
        env:
          GH_TOKEN: ${{ secrets.github_token }}
          
      - name: Output Linux
        uses: actions/upload-artifact@v2-preview
        if: "!startsWith(github.ref, 'refs/tags/@betaflight/configurator@')"
        with:
          name: linux
          path: packages/configurator/dist/*.snap

      - name: Output Windows
        uses: actions/upload-artifact@v2-preview
        if: "!startsWith(github.ref, 'refs/tags/@betaflight/configurator@')"
        with:
          name: windows
          path: packages/configurator/dist/*.msi

      - name: Output MacOS
        uses: actions/upload-artifact@v2-preview
        if: "!startsWith(github.ref, 'refs/tags/@betaflight/configurator@')"
        with:
          name: macos
          path: |
            packages/configurator/dist/*.dmg
